service: backend
runtime: python311
env: standard
entrypoint: daphne -p 8000 -b 0.0.0.0 smart_chat_backend.asgi:application


env_variables:
  # This setting is used in settings.py to configure your ALLOWED_HOSTS
  APPENGINE_URL: backend-dot-smart-chat-383601.wl.r.appspot.com

handlers:
- url: /.*
  script: auto

runtime_config:
  python_version: 3
