service: backend
runtime: python
env: flex
entrypoint: daphne -p $PORT -b 0.0.0.0 smart_chat_backend.asgi:application

manual_scaling:
  instances: 1

env_variables:
  APPENGINE_URL: backend-dot-smart-chat-383601.wl.r.appspot.com

runtime_config:
    runtime_version: "3.11"

beta_settings:
  cloud_sql_instances: smart-chat-383601:us-west2:cc-pg-db-us-west-2

network:
  session_affinity: true