service: backend
runtime: python311
env: flex
entrypoint: daphne -p $PORT -b 0.0.0.0 smart_chat_backend.asgi:application

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

env_variables:
  APPENGINE_URL: backend-dot-smart-chat-383601.wl.r.appspot.com

runtime_config:
  python_version: 3
