name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15'
      
      - name: Node Version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: smart-chat
