name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15'
      
      - name: Node Version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: smart-chat
          service: smart-chat-frontend
          config: ./app.yaml
          source: ./build
