name: Deploy to ECS

on:
  push:
    branches:
      - that-does-not-exist # skip all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /smart_chat/scripts && ./setup.sh && ./deployment.sh &"

