name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save EC2 Private Key
        run: |
          echo -n "$SSH_PRIVATE_KEY" > temp_key.pem && chmod 600 temp_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote host to known hosts
        run: mkdir -p ~/.ssh && ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i temp_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd ~/smart_chat/scripts && chmod +x ./setup.sh && chmod +x ./deployment.sh && bash ./setup.sh && bash ./deployment.sh &"

